name: deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: [update-data]
    types:
      - completed

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: src

      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - run: npm install

      - run: scripts/deploy.sh
