name: deploy-main

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'
  workflow_run:
    workflows: [update-main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: src

      - uses: FedericoCarboni/setup-ffmpeg@v3
        id: setup-ffmpeg

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install --prefix lat

      - run: npm install --prefix main

      - name: Cache build artifacts
        id: cache-build
        uses: actions/cache@v4
        with:
          path: |
            main/build
            main/out
          key: main

      - run: node lat deploy main --cf-prod --yes
