name: deploy-main

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'
  workflow_run:
    workflows: [update-main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: src

      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - run: npm install

      - name: Cache build artifacts
        id: cache-build
        uses: actions/cache@v3
        with:
          path: out
          key: out

      - run: node lathala deploy main --yes
