name: update-data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    environment: update-data

    steps:
      - uses: actions/checkout@v3
        with:
          ref: src

      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - run: npm install

      - run: scripts/update.sh
        env:
          GOATCOUNTER_API_KEY: ${{ secrets.GOATCOUNTER_API_KEY }}
