name: update-main

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 */3 * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: src

      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - run: npm install --prefix main

      - run: main/scripts/update/update.sh
